#                                                              -*- Makefile -*-
# Simics module makefile
#

MODULE_COMPONENTS := pci_indicator_card

SIMICS_API := latest
THREAD_SAFE:=yes
PYTHON_FILES = pci_indicator_component.py module_load.py

include $(MODULE_MAKEFILE)
